apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-master
    spec:
      containers:
        - name: postgres-master
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-master-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-master-volume
          lifecycle:
            postStart:
              exec:
                 command: 
                   - "/bin/sh"
                   - "-c"
                   - >
                     apt-get update;
                     apt-get install wget -y;
                     runuser -l postgres -c 'cd /tmp/ ; wget http://pgfoundry.org/frs/download.php/527/world-1.0.tar.gz ; tar xzf world-1.0.tar.gz ; psql postgresdb -c "CREATE TABLE city (id integer NOT NULL, name text NOT NULL, countrycode character(3) NOT NULL, district text NOT NULL, population integer NOT NULL); CREATE PUBLICATION mypub FOR TABLE city;" ; psql postgresdb < dbsamples-0.1/world/world.sql';
      volumes:
        - name: postgres-master-volume
          persistentVolumeClaim:
            claimName: postgres-master-claim
