kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-master-volume
  labels:
    type: local
    app: postgres-master
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/postgres-master"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-master-claim
  labels:
    app: postgres-master
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
