apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-master
    spec:
      hostNetwork: true
      nodeSelector:
        app: postgres-master
      containers:
        - name: postgres-master
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: pg
              containerPort: 5432
              hostPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-master-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-master-volume
            - mountPath: /docker-entrypoint-initdb.d
              name: init-db
      volumes:
        - name: postgres-master-volume
          persistentVolumeClaim:
            claimName: postgres-master-claim
        - name: init-db
          configMap:
            name: postgres-master-initdb
