apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-master-config
  labels:
    app: postgres-master
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: postgrespassword
