kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-slave-volume
  labels:
    type: local
    app: postgres-slave
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/postgres-slave"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-slave-claim
  labels:
    app: postgres-slave
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
