apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-slave-config
  labels:
    app: postgres-slave
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: postgrespassword
