---

- name: Change sudoers and disable swap
  hosts: all
#  become: yes
#  become_method: sudo
  roles:
    - sudoers
    - swap

- name: Prepare ssh
  hosts: all
  roles:
    - ssh-key

- name: Install docker and kubernetes
  hosts: all
#  become: yes
#  become_method: sudo
  roles:
    - docker
    - kubernetes

- name: Create etcd cluster
  hosts: master
#  become: yes
#  become_method: sudo
  roles:
    - etcd

- name: Init cluster
  hosts: master
#  become: yes
#  become_method: sudo
  roles:
    - master

- name: Install weavenet
  hosts: master
  roles:
    - weavenet

- name: Add workes to cluster
  hosts: worker
#  become: yes
#  become_method: sudo
  roles:
    - worker
